/**
 * Created by chenjie on 2018/4/3.
 */
const titleStyle={
  background: '#f5f9fc',
  color: '#000002',
  width:'5.88%'
};
const dataStyle={
  color: '#00ccfb',
  width:'5.88%'
};
export default {
  saveTable:true,
  tBodyArr:[
    {
      tds: [
        {
          name:'单位名称',
          col:3,
          style:titleStyle
        },
        {
          name:'12',
          col:7,
          style:dataStyle
        },
        {
          name:'主管部门',
          col:2,
          style:titleStyle
        },
        {
          name:12,
          col:5,
          style:dataStyle
        }
      ]
    },
    {
      tds: [
        {
          name:'单位规格',
          col:3,
          style:titleStyle
        },{
          name:12,
          col:3,
          style:dataStyle
        },{
          name:'经费来源',
          col:2,
          style:titleStyle
        },{
          name:12,
          col:2,
          style:dataStyle
        },{
          name:'定编文号及时间',
          col:2,
          style:titleStyle
        },{
          name:12,
          col:5,
          style:dataStyle
        }
      ]
    },
    {
      tds:[
        {
          name:"编制数",
          col:3,
          row:2,
          style:titleStyle
        },{
          name:12,
          col:3,
          row:2,
          style:dataStyle
        },{
          name:'领导职数',
          col:2,
          row:2,
          style:titleStyle
        },{
          name:12,
          col:2,
          row:2,
          style:dataStyle
        },{
          name:'内设机构个数',
          col:2,
          style:titleStyle
        },{
          name:4,
          col:5,
          style:dataStyle
        }
      ]
    },
    {
      tds:[
        {
          name:'内设机构领导职数',
          col:2,
          style:titleStyle
        },{
          name:12,
          col:5,
          style:dataStyle
        }
        ]
    },
    {
      tds:[
        {
          name:'管理人员',
          row:2,
          style:titleStyle
        },{
          name:'级别',
          col:2,
          style:titleStyle
        },{
          name:'厅级正职',
          style:titleStyle
        },{
          name:'厅级副职',
          style:titleStyle
        },{
          name:'局级正职',
          style:titleStyle
        },{
          name:'局级副职',
          style:titleStyle
        },{
          name:'处级正职',
          style:titleStyle
        },{
          name:'处级副职',
          style:titleStyle
        },{
          name:'科级正职',
          style:titleStyle
        },{
          name:'科级副职',
          style:titleStyle
        },{
          name:'科员',
          style:titleStyle
        },{
          name:'办事员',
          style:titleStyle
        },{
          name:'未定级',
          style:titleStyle
        }
      ]
    },
    {
      tds:[
        {
          name:'现聘人数',
          col:2,
          style:titleStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        },{
          name:123,
          style:dataStyle
        }
      ]
    },
    {
      tds:[
        {
          name:'现有在册人数总数',
          col:3,
          style:titleStyle
        },{
          name:'类别',
          col:3,
          style:titleStyle
        },{
          name:'管理人员',
          col:3,
          style:titleStyle
        },{
          name:'专业技术人员',
          col:3,
          style:titleStyle
        },{
          name:'工勤人员',
          col:3,
          style:titleStyle
        },
      ]
    },
    {
      tds:[
        {
          name:12,
          col:3,
          row:2,
          style:dataStyle
        },{
          name:'人数',
          col:3,
          style:titleStyle
        },{
          name:10,
          col:3,
          style:dataStyle
        },{
          name:10,
          col:3,
          style:dataStyle
        },{
          name:10,
          col:3,
          style:dataStyle
        }
      ]
    },
    {
      tds:[
        {
          name:'占人员总比例',
          col:3,
          style:titleStyle
        },{
          name:'10%',
          col:3,
          style:dataStyle
        },{
          name:10,
          col:3,
          style:dataStyle
        },{
          name:10,
          col:3,
          style:dataStyle
        }
      ]
    }
  ]
}
